# Site settings
title: DOT.
description: 'Belajar memahami code dan IoT'
url: 'https://www.dot.or.id'
baseurl: ''
profilepic: '/images/logo.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '53d7a3a62b.js'

author:
  name: 'DOT.'
  email: staff@dot.or.id
  mastodon: 
  twitter_username: 
#  facebook_username: 
  github_username:  
  linkedin_username:  
  meetup_name: 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
